// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  footer: string;
  text2: string;
}
export const cssExports: CssExports;
export default cssExports;
