// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'err': string;
  'errorText': string;
  'errorWhiteText': string;
  'imagee': string;
  'layout': string;
  'root': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
